### ISSUE TITLE
Data test sequence invalid syntax for Oracle DB

### ISSUE THREAD

**Issue by vitoravancini** [dbt-labs/dbt-adapter-tests#17]
Hello everyone,

the builtin data test sequence runs this 2 tests:

```
--passing.sql:
select 1 as id where id = 1

--failing.sql:
select 1 as id where id = 2
```

This syntax  is not valid for Oracle DB, do you have any suggestion on how to overwrite this?

Thank you for this project, made my life a lot easier for testing the adapter. See you!

**Comment by jtcohen6** [comment]
Hey @vitoravancini, thanks for your work building an Oracle adapter, and for checking out the test suite!

You can override this right in your spec file, using the `projects.overrides` key:
```yml
projects:
  # data test syntax needs fixing
  - overrides: data_test
    paths:
      test/passing.sql: |
        select 1 as id where true
      test/failing.sql: |
        select 1 as id where false
```

Out of curiosity, what is the syntactical issue that prevents that code from working on Oracle?
